export const BluesLogo = require('@/store/SuperRugbyTeamLogos/Blues_Super_Rugby_Logo.png')
export const BrumbiesLogo = require('@/store/SuperRugbyTeamLogos/Brumbies_Rugby_logo.png')
export const ChiefsLogo = require('@/store/SuperRugbyTeamLogos/Chiefs_rugby_logo.png')
export const CrusadersLogo = require('@/store/SuperRugbyTeamLogos/Crusaders_Rugby_Logo.png')
export const DruaLogo = require('@/store/SuperRugbyTeamLogos/Fijian_Drua_Logo.png')
export const HighlandersLogo = require('@/store/SuperRugbyTeamLogos/Highlanders_NZ_rugby_logo.png')
export const HurricanesLogo = require('@/store/SuperRugbyTeamLogos/Hurricanes_logo.png')
export const RebelsLogo = require('@/store/SuperRugbyTeamLogos/Melbourne_Rebels_logo.png')
export const MoanaLogo = require('@/store/SuperRugbyTeamLogos/Moana_Pasifika_logo.png')
export const RedsLogo = require('@/store/SuperRugbyTeamLogos/QLD_reds_logo.png')
export const WaratahsLogo = require('@/store/SuperRugbyTeamLogos/Waratahs_logo.png')
export const ForceLogo = require('@/store/SuperRugbyTeamLogos/Western_force_rugby_logo.png')

