import { ArgentinaLogo, AustraliaLogo, BALionsLogo, CanadaLogo, ChileLogo, DefaultLogo, EnglandLogo, FijiLogo, FranceLogo, GeorgiaLogo, IrelandLogo, ItalyLogo, JapanLogo, NamibiaLogo, NewZealandLogo, PortugalLogo, RomaniaLogo, RussiaLogo, SamoaLogo, ScotlandLogo, SouthAfricaLogo, SpainLogo, TongaLogo, UruguayLogo, USALogo, WalesLogo } from "./InternationalTeamLogos/InternationalTeams";

export const getInternationalTeamInfoFromName = (name: string) => {

  const defaultTeam =  {
    type: 'International',
    displayName: 'Default',
    abbreviation: 'DEF',
    logo: DefaultLogo,
    altLogo: DefaultLogo,
    colour: '#00845c',
    id: '0',
    defaultLeague: '',
    foundedYear: '',
    seasonType: '',
  }

    const match = InternationalRugbyTeams.find((item) => item.displayName === name)
    if(match !== undefined)
    {
        return match
    }
    else
    {
        return defaultTeam
    }
}

export const InternationalRugbyTeams = [
  {
    type: 'International',
    displayName: 'Ireland',
    abbreviation: 'IRE',
    logo: IrelandLogo,
    colour: '#00845c',
    id: '3',
    defaultLeague: 'Six Nations',
    foundedYear: '1875',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'South Africa',
    abbreviation: 'SA',
    logo: SouthAfricaLogo,
    colour: '#006400',
    id: '5',
    defaultLeague: 'Rugby Championship',
    foundedYear: '1891',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'England',
    abbreviation: 'ENG',
    logo: EnglandLogo,
    colour: '#ffffff',
    id: '1',
    defaultLeague: 'Six Nations',
    foundedYear: '1871',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'New Zealand',
    abbreviation: 'NZL',
    logo: NewZealandLogo,
    colour: '#ffffff',
    id: '8',
    defaultLeague: 'Rugby Championship',
    foundedYear: '1884',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Australia',
    abbreviation: 'AUS',
    logo: AustraliaLogo,
    colour: '#ffbb00',
    id: '6',
    defaultLeague: 'Rugby Championship',
    foundedYear: '1899',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'France',
    abbreviation: 'FRA',
    logo: FranceLogo,
    colour: '#003b7c',
    id: '9',
    defaultLeague: 'Six Nations',
    foundedYear: '1893',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Scotland',
    abbreviation: 'SCOT',
    logo: ScotlandLogo,
    colour: '#ffbb00',
    id: '2',
    defaultLeague: 'Six Nations',
    foundedYear: '1871',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Wales',
    abbreviation: 'WALES',
    logo: WalesLogo,
    colour: '#d21034',
    id: '4',
    defaultLeague: 'Six Nations',
    foundedYear: '1881',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Italy',
    abbreviation: 'ITALY',
    logo: ItalyLogo,
    colour: '#ffffff',
    id: '20',
    defaultLeague: 'Six Nations',
    foundedYear: '1911',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Argentina',
    abbreviation: 'ARG',
    logo: ArgentinaLogo,
    colour: '#43a1d5',
    id: '10',
    defaultLeague: 'Rugby Championship',
    foundedYear: '1910',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Japan',
    abbreviation: 'JPN',
    logo: JapanLogo,
    colour: '#f4d5e2',
    id: '23',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1932',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Georgia',
    abbreviation: 'GEO',
    logo: GeorgiaLogo,
    colour: '#551828',
    id: '81',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1959',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Fiji',
    abbreviation: 'FIJI',
    logo: FijiLogo,
    colour: '#ffffff',
    id: '14',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1913',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Canada',
    abbreviation: 'CAN',
    logo: CanadaLogo,
    colour: '#e82042',
    id: '25',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1932',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'United States of America',
    abbreviation: 'USA',
    logo: USALogo,
    colour: '#0a3161',
    id: '11',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1976',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Romania',
    abbreviation: 'ROM',
    logo: RomaniaLogo,
    colour: '#002b7f',
    id: '12',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1924',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Portugal',
    abbreviation: 'POR',
    logo: PortugalLogo,
    colour: '#046a38',
    id: '27',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1935',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Namibia',
    abbreviation: 'NAMIB',
    logo: NamibiaLogo,
    colour: '#001489',
    id: '82',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1916',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Tonga',
    abbreviation: 'TONGA',
    logo: TongaLogo,
    colour: '#ed1c24',
    id: '16',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1924',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Samoa',
    abbreviation: 'SAMOA',
    logo: SamoaLogo,
    colour: '#264282',
    id: '15',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1924',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Spain',
    abbreviation: 'ESP',
    logo: SpainLogo,
    colour: '#ffcc00',
    id: '18',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1929',
    seasonType: 'north',
  },
  {
    type: 'International',
    displayName: 'Chile',
    abbreviation: 'CHILE',
    logo: ChileLogo,
    colour: '#0032a0',
    id: '28',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1936',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Uruguay',
    abbreviation: 'URUG',
    logo: UruguayLogo,
    colour: '#0038a8',
    id: '29',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1948',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'Russia',
    abbreviation: 'RUS',
    logo: RussiaLogo,
    colour: '#ffff',
    id: '',
    defaultLeague: 'Rugby World Cup',
    foundedYear: '1974',
    seasonType: 'south',
  },
  {
    type: 'International',
    displayName: 'British and Irish Lions',
    abbreviation: 'LIONS',
    logo: BALionsLogo,
    colour: '#d21034',
    id: '32',
    defaultLeague: '',
    foundedYear: '1888',
    seasonType: 'north',
  },
];