import { DefaultLogo } from "./InternationalTeamLogos/InternationalTeams"
import { BenettonLogo, BullsLogo, CardiffLogo, ConnachtLogo, DragonsLogo, EdinburghLogo, GlasgowLogo, LeinsterLogo, LionsLogo, MunsterLogo, OspreysLogo, ScarletsLogo, SharksLogo, StormersLogo, UlsterLogo, ZebreLogo } from "./URCTeamLogos/URCTeams"


export const getURCTeamInfoFromName = (name: string) => {

  const defaultTeam =  {
    type: 'URC Club',
    displayName: 'Default',
    abbreviation: 'DEF',
    logo: DefaultLogo,
    colour: '#00845c',
    id: '0',
    defaultLeague: '',
    foundedYear: '',
    seasonType: '',
  }
    const match = URCRugbyTeams.find((item) => item.displayName === name)
    if(match !== undefined)
    {
        return match
    }
    else
    {
        return defaultTeam
    }
}


export const URCRugbyTeams = [
  {
    type: 'URC Club',
    displayName: 'Leinster',
    abbreviation: 'LEINS',
    logo: LeinsterLogo,
    colour: '#003287',
    id: '25924',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1879',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Munster',
    abbreviation: 'MUNST',
    logo: MunsterLogo,
    colour: '#cd0a2d',
    id: '25925',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1879',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Connacht',
    abbreviation: 'CONN',
    logo: ConnachtLogo,
    colour: '#00b446',
    id: '25923',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1885',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Ulster',
    abbreviation: 'ULST',
    logo: UlsterLogo,
    colour: '#e61d03',
    id: '25926',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1879',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Edinburgh',
    abbreviation: 'EDINB',
    logo: EdinburghLogo,
    colour: '#1e144b',
    id: '25951',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1872',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Glasgow Warriors',
    abbreviation: 'GLASG',
    logo: GlasgowLogo,
    colour: '#5aaaf0',
    id: '25952',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1872',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Cardiff Blues',
    abbreviation: 'CDB',
    logo: CardiffLogo,
    colour: '#6ebeff',
    id: '25965',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '2003',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Scarlets',
    abbreviation: 'SCARL',
    logo: ScarletsLogo,
    colour: '#78040d',
    id: '25966',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '2003',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Ospreys',
    abbreviation: 'OSP',
    logo: OspreysLogo,
    colour: '#5a5a64',
    id: '25968',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '2003',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Dragons',
    abbreviation: 'DRA',
    logo: DragonsLogo,
    colour: '#ffaa00',
    id: '25967',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '2003',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Benetton Treviso',
    abbreviation: 'TRE',
    logo: BenettonLogo,
    colour: '#00b46f',
    id: '25927',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1932',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Zebre',
    abbreviation: 'ZEB',
    logo: ZebreLogo,
    colour: '#233268',
    id: '167124',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1973',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Stormers',
    abbreviation: 'STORM',
    logo: StormersLogo,
    colour: '#005295',
    id: '25962',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1997',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Bulls',
    abbreviation: 'BULLS',
    logo: BullsLogo,
    colour: '#0082e6',
    id: '25953',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1997',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Lions',
    abbreviation: 'LIONS',
    logo: LionsLogo,
    colour: '#ff1e29',
    id: '25958',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1996',
    seasonType: 'north',
  },
  {
    type: 'URC Club',
    displayName: 'Sharks',
    abbreviation: 'SHARK',
    logo: SharksLogo,
    colour: '#504b50',
    id: '25961',
    defaultLeague: 'United Rugby Championship',
    foundedYear: '1995',
    seasonType: 'north',
  },

];