export const IrelandLogo = require('@/store/InternationalTeamLogos/Irish_Rugby_Football_Union_logo.png')
export const SouthAfricaLogo = require('@/store/InternationalTeamLogos/South_Africa_national_rugby_union_team.png')
export const EnglandLogo = require('@/store/InternationalTeamLogos/England_national_rugby_team_logo.png')
export const NewZealandLogo = require('@/store/InternationalTeamLogos/All_Blacks_logo.png')
export const AustraliaLogo = require('@/store/InternationalTeamLogos/Logo_Wallabies.png')
export const WalesLogo = require('@/store/InternationalTeamLogos/Welsh_Rugby_Union_logo.png')
export const FranceLogo = require('@/store/InternationalTeamLogos/France_Rugby_logo.png')
export const ScotlandLogo = require('@/store/InternationalTeamLogos/Scotlandlogo.png')
export const ArgentinaLogo = require('@/store/InternationalTeamLogos/Los_pumas_argentina_logo.png')
export const ItalyLogo = require('@/store/InternationalTeamLogos/Italian_Rugby_Federation_logo.png')
export const FijiLogo = require('@/store/InternationalTeamLogos/Logo_Fiji_Rugby.png')
export const JapanLogo = require('@/store/InternationalTeamLogos/Logo_Japan_Rugby.png')
export const GeorgiaLogo = require('@/store/InternationalTeamLogos/Georgian_Rugby_Union.png')
export const PortugalLogo = require('@/store/InternationalTeamLogos/Portuguese_Rugby_Logo.png')
export const CanadaLogo = require('@/store/InternationalTeamLogos/Rugby_Canada_logo.png')
export const USALogo = require('@/store/InternationalTeamLogos/United_States_national_rugby_union_team_logo.png')
export const ChileLogo = require('@/store/InternationalTeamLogos/Condores_Chile_Rugby.png')
export const NamibiaLogo = require('@/store/InternationalTeamLogos/Logo_Namibia_Rugby.png')
export const TongaLogo = require('@/store/InternationalTeamLogos/Logo_Tonga_Rugby.png')
export const SamoaLogo = require('@/store/InternationalTeamLogos/Logo_Samoa_Rugby.png')
export const RomaniaLogo = require('@/store/InternationalTeamLogos/Romania_national_rugby_union_team_logo.png')
export const SpainLogo = require('@/store/InternationalTeamLogos/Spain_Rugby_logo.png')
export const UruguayLogo = require('@/store/InternationalTeamLogos/Uruguay_Los_teros_logo.png')
export const BALionsLogo = require('@/store/InternationalTeamLogos/British_&_Irish_Lions_logo.png')

export const DefaultLogo = require('@/store/InternationalTeamLogos/Default_Team_Logo.png')

